from pathlib import Path
from os import environ, getuid

LOG_TIME_FORMAT = '%Y-%m-%d %H:%M:%S %z'
FALLBACK_CONTAINER_IMAGE = f'localhost/ansible-executor:{getuid()}'

DEFAULT_LOG_DIR = Path(f"{environ.get('HOME', '')}/.local/share/oxl-ansible-executor")

# names AND cli-executable
CONTAINER_ENGINE_DOCKER = 'docker'
CONTAINER_ENGINE_PODMAN = 'podman'
CONTAINER_ENGINES = (CONTAINER_ENGINE_DOCKER, CONTAINER_ENGINE_PODMAN)

SELECTOR_STATS_RECAP_BEGIN = '__AR_STATS_RECAP_BEGIN__'
SELECTOR_STATS_RECAP_END = '__AR_STATS_RECAP_END__'
SELECTOR_STATS_LIVE_BEGIN = '__AR_STATS_LIVE_BEGIN__'
SELECTOR_STATS_LIVE_END = '__AR_STATS_LIVE_END__'
CALLBACK_PLUGIN_STATS_LIVE = 'oxl_executor_stats_live'
CALLBACK_PLUGIN_STATS_RECAP = 'oxl_executor_stats_recap'

ENV_ANSIBLE_CALLBACK_PLUGINS = 'ANSIBLE_CALLBACK_PLUGINS'
ENV_ANSIBLE_CALLBACKS_ENABLED = 'ANSIBLE_CALLBACKS_ENABLED'
