[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oxl-ansible-executor"
authors = [
    {name = "Pascal Rath", email = "rath@oxl.at"},
]
description = "Simple & Transparent Executor for Ansible-Playbooks"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["ansible", "executor", "runner", "automation", "iac"]
license = {file = "LICENSE.txt"}
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Framework :: Ansible',
]
dynamic = ["dependencies", "version"]

[project.urls]
Homepage = "https://github.com/O-X-L/ansible-executor"
Documentation = "https://ansible-executor.OXL.app/"
Repository = "https://github.com/O-X-L/ansible-executor.git"
Issues = "https://github.com/O-X-L/ansible-executor/issues"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {file = ["VERSION"]}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["*_pytest.py"]

[tool.setuptools.package-data]
"*" = ["Dockerfile*"]
