---

name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/integration_test.yml'

  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/integration_test.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # see: https://docs.ansible.com/projects/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
          - ansible_core_version: '2.18'
            ar_engine: 'local'
          - ansible_core_version: '2.18'
            ar_engine: 'docker'

          - ansible_core_version: '2.19'
            ar_engine: 'local'
          - ansible_core_version: '2.19'
            ar_engine: 'docker'

          - ansible_core_version: '2.20'
            ar_engine: 'local'
          - ansible_core_version: '2.20'
            ar_engine: 'docker'

    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install -r requirements_build.txt >/dev/null
          sudo apt install python3-virtualenv python3-pip >/dev/null

      - name: Preparing test-env
        run: |
          echo 'CREATING TMP VENV'
          python3 -m virtualenv "$AR_VENV" >/dev/null
          source "${AR_VENV}/bin/activate"

          echo 'INSTALLING DEPENDENCIES'
          pip install ansible-core==${{ matrix.ansible_core_version }}.* >/dev/null

          echo 'INSTALLING MODULE'
          python3 -m pip install -e "$GITHUB_WORKSPACE" >/dev/null
        env:
          AR_VENV: '/tmp/ar_venv'

      - name: Running Integration Tests
        run: |
          source "${AR_VENV}/bin/activate"
          python3 ${GITHUB_WORKSPACE}/test/integration.py
        env:
          PYTHONUNBUFFERED: 1
          AR_TEST: 1
          AR_VENV: '/tmp/ar_venv'
          AR_TEST_VERBOSE: 0
          AR_TEST_ENGINE: "${{ matrix.ar_engine }}"
