---

name: Unit-Tests

on:
  workflow_dispatch:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'requirements_unit_test.txt'
      - '.github/workflows/unit_test.yml'

  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'requirements_unit_test.txt'
      - '.github/workflows/unit_test.yml'

jobs:
  test:
    strategy:
      matrix:
        include:
          # see: https://docs.ansible.com/projects/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
          - python_version: '3.11'
          - python_version: '3.12'
          - python_version: '3.13'
          - python_version: '3.14'

    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install dependencies
        run: |
          pip install -r requirements_unit_test.txt >/dev/null
          pip install ansible-core  # is not executed 

      - name: Running Unit Tests
        run: |
          pytest --version
          python3 -m pytest
        env:
          PYTHONUNBUFFERED: 1
          AR_TEST: 1
