LOG_TIME_FORMAT = '%Y-%m-%d %H:%M:%S %z'
CONTAINER_ENGINE_DOCKER = 'docker'
CONTAINER_ENGINE_PODMAN = 'podman'
CONTAINER_ENGINES = (CONTAINER_ENGINE_DOCKER, CONTAINER_ENGINE_PODMAN)
FALLBACK_CONTAINER_IMAGE = 'oxlorg/ansible-executor'
